# version of docker-compose syntax
version: "3.9"

services:
  # service "app" will run our docker file
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    # automatically sync the code in our project to the code in our container
    volumes:
      - ./app:/app
    # command that is used to run the service
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
  
    
      
